# Generated by Django 5.0.3 on 2024-03-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_team_is_automated'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
