# Generated by Django 5.0.3 on 2024-03-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyticketpurchase',
            name='projection',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticketpurchase',
            name='projection',
            field=models.IntegerField(default=0),
        ),
    ]
