# Generated by Django 5.0.3 on 2024-03-28 00:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_ticketpurchase_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketpurchase',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticketpurchase',
            name='purchase_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 28, 0, 50, 34, 282596)),
        ),
    ]
